### ISSUE TITLE
悬链线的工程应用

### ISSUE THREAD

**Issue by redtankbai** [PrimerLi/catenary#1]
Hi，感谢你提供的悬链线 PY 脚本，看了之后获益良多

目前还有个问题，就是需要计算任意长度刚体组成的链条，两端固定在不同高度时，每段刚体的两端位置，而且需要能在 3D 空间坐标描述

请问有没有什么办法或者参考资料？谢谢！

**Comment by redtankbai** [comment]
换个表述方式以防混淆：
已知两个 3D 空间坐标和一条由不等长线段组成的链条的每段长度，要求能生成一组能拟合悬链线的坐标，来用于放置链条的每一段，并且首尾能和给定的两个坐标尽可能重合

求助，谢谢！

**Comment by PrimerLi** [comment]
你仍然可以用最小能量原理解这个问题，跟我的那个没有什么区别。如果各段刚体之间是用光滑的铰链链接，那么这个3 D空间中的悬链线其实还是在一个二维平面上。

2018-08-07 12:18 GMT-07:00 redtank <notifications@github.com>:

**Comment by redtankbai** [comment]
我现在没想明白的是，如何知道生成的曲线能通过给定点，并且长度和链条总长度相似

**Comment by redtankbai** [comment]
在仔细看了你给的PDF图片后，发现从视觉上，你的计算结果是两端的线段更长，而靠近底部的线段更短，似乎并没有能固定住线段长度，请教

**Comment by PrimerLi** [comment]
我在文档里面写了，我使用了拉格朗日乘子法来约束链条的终点坐标。因为终点坐标有两个自由度，所以我用了两个拉格朗日乘子。视觉上确实有这个问题，那是因为画图软件为了美观，在作图的时候没有将横轴方向和纵轴方向按照1:1的比例绘制。其实这些线段的长度都是一样的。

2018-08-07 12:54 GMT-07:00 redtank <notifications@github.com>:

**Comment by redtankbai** [comment]
https://math.stackexchange.com/questions/1000447/finding-the-catenary-curve-with-given-arclength-through-two-given-points
我找到一个相关的英文讨论，但我数学能力有限，不知道你有没有时间看看，转成 py 代码？

**Comment by PrimerLi** [comment]
这个只适用于连续的绳索，不适用于铁链。这就是大一水平的高数，应该不难。我也没空写。
